change to .c file to avoid build error issue
```
(base) tonyho@ubuntu5:~/workspace/gcc_study/union$ gcc union.cpp
union.cpp: In function ‘int main()’:
union.cpp:32:9: error: expected primary-expression before ‘.’ token
   32 |         .data.description = "red"
      |         ^
union.cpp:37:9: error: expected primary-expression before ‘.’ token
   37 |         .data.description = "orange"
      |         ^
union.cpp:42:9: error: expected primary-expression before ‘.’ token
   42 |         .data.rgb = { 245, 245, 220 }
      |         ^
```